using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.0.1.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aqueduct 2007-2012")]
[assembly: AssemblyCompanyAttribute("Aqueduct")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyInformationalVersionAttribute("0.0.1.0")]

